### PR TITLE
first pass

### PR DESCRIPTION
**Pull request by lisazacarias**

### CODE REVIEW

**Review by jjanice — APPROVED** [review]
Lines 65-67 of sel_phase_linac - the get to fetch the latest value of the PVs in part of the return statement in the class definitions a la line 33?
The chisum calc (lines 71-72) relies on slop and should be under the check for if not np.isnan(slop) line 73. 
I like how the code just does nothing if isnan(slop).  Pretty funny.  Someone (me! me!) really didn't think it through. 
In sel_phase_optimizer line 34 I need help parsing. The if clause is for the 1? else num_large_steps+=0?
Sweet of you to keep the "Thanks for your help!" silliness. 
None of these are show stoppers. The silly code has run hundreds of times.

**Comment by jjanice** [comment]
thank you for doing this! You make it look so easy!

**Comment by lisazacarias** [comment]
> In sel_phase_optimizer line 34 I need help parsing. The if clause is for the 1? else num_large_steps+=0?

Yeah it returns true if it wanted to take a step larger than 5, so I'm only incrementing the counter if that was the case

**Comment by jjanice** [comment]
Thank you thank you!!

**Pull request merged**
